export const COMPLAINT_STATUS = {
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  REOPEN_REQUESTED: "REOPEN_REQUESTED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
};

export const COMPLAINT_CATEGORIES = [
  "PLUMBING",
  "ELECTRICAL",
  "LIFT",
  "CLEANING",
  "SECURITY",
  "PARKING",
  "GARDENING",
  "OTHER",
];

// Actions for ComplaintHistory
export const COMPLAINT_ACTIONS = {
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
  STARTED: "STARTED",
  RESOLVED: "RESOLVED",
  REOPEN_REQUESTED: "REOPEN_REQUESTED",
  REOPEN_APPROVED: "REOPEN_APPROVED",
  REOPEN_REJECTED: "REOPEN_REJECTED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
  FEEDBACK_SUBMITTED: "FEEDBACK_SUBMITTED",
};
